//
// Created by cgsdfc on 19-6-7.
//

#ifndef ITERTOOLS_VERSION_H
#define ITERTOOLS_VERSION_H

#define ITERTOOLS_VERSION_MAJOR 1
#define ITERTOOLS_VERSION_MINOR 1
#define ITERTOOLS_VERSION_PATCH 0

#define ITERTOOLS_VERSION 101000
#define ITERTOOLS_VERSION_STRING #ITERTOOLS_VERSION

#endif //ITERTOOLS_VERSION_H
